export enum Category {
  ALIMENTATION = 'ALIMENTATION',
  DIVERTISSEMENT = 'DIVERTISSEMENT',
  LOYER = 'LOYER',
  FACTURES = 'FACTURES',
  TRANSPORT = 'TRANSPORT',
  SANTE = 'SANTE',
  EDUCATION = 'EDUCATION',
  ACHATS = 'ACHATS',
  VOYAGE = 'VOYAGE',
  RESTAURANT = 'RESTAURANT'
}
